# -*- coding: utf-8 -*-
"""prgm 17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fqHVAVKuYJbZwuc4IY1Pgyrzi2ZqOb6Z
"""

import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt

student = pd.read_csv('/content/student_scores.csv')
print(student.head())
print(student.describe())
print(student.info())

Xax = student.iloc[:,0]
Yax = student.iloc[:,1]
plt.scatter(Xax,Yax)
plt.xlabel('Number of hours')
plt.ylabel('Scores')
plt.title("Student Scores")
plt.show()

from re import X
Xax = student.iloc[:,0]
Yax = student.iloc[:,1]
print('x values :\n',Xax)
print('y values :\n',Yax)

X_train, X_test, y_train, y_test = train_test_split(Xax, Yax, test_size=0.2,
random_state=42)
X_train = X_train.values.reshape(-1, 1)
X_test = X_test.values.reshape(-1, 1)
regressor = LinearRegression()
regressor.fit(X_train, y_train)
print('INTERCEPT=',regressor.intercept_)
print('COEFFICIENT=',regressor.coef_)

y_pred = regressor.predict(X_test)
print("Actual vs Predicted values:")
for actual,predicted in zip(y_test,y_pred):
  print(f"Actual value:{actual},Predicted:{predicted}")

mislabeled_points = np.sum(np.round(y_test) != np.round(y_pred))
print("NUmber of mislabeled points:",mislabeled_points)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("Mean Squared Error:",mse)
print("R_squared:",r2)
