# -*- coding: utf-8 -*-
"""Prgm5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lTu0tak5Bq4dV0mG47FXRP2bsfjEIMah
"""

import numpy as np
A=np.array([[2,1,-1],[3,0,1],[1,1,-1]])
B=np.array([-3,5,-2])
X=np.linalg.solve(A,B)
print("Matrix A:")
print(A)
print("Vector B:")
print(B)
print("Solution for X:")
print(X)