# -*- coding: utf-8 -*-
"""prgm20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oC8987LCp2cTvwwS0YISJkWGj_W5hCke
"""

import requests
from bs4 import BeautifulSoup

print("Batch : MCA 2023-25")

def getdata(url):
    r = requests.get(url)
    return r.content

url="https://www.w3schools.com/python/default.asp"
htmldata = getdata(url)

soup = BeautifulSoup(htmldata, 'html.parser')

paragraphs = soup.find_all('p')
print("<P> tag count:", len(paragraphs))

for p in paragraphs:
    print(p.get_text())